Convert client to clean architecture
FIAP-6SOAT-G10/tech-challenge-fase-2 pull request #6
Opened 2024-07-11 21:57 UTC by Getnerski

2024-07-11 22:29 UTC, magneon requested changes
Só precisa alterar na camada de infra o retorno do controller. No caso, o retorno é sempre DTO pois refere-se a camada de infra "presenters"

2024-07-11 22:29 UTC, magneon commented on src/main/java/br/com/fiap/techchallenge/infra/controllers/ClienteController.java
> +    public ResponseEntity<List<Cliente>> listarTodosClientes(@RequestParam Integer page,
O retorno aqui precisa ser um ClienteDTO, não pode ser um Cliente da entidade de domínio.

2024-07-11 22:38 UTC, Getnerski commented on src/main/java/br/com/fiap/techchallenge/infra/controllers/ClienteController.java
> +    public ResponseEntity<List<Cliente>> listarTodosClientes(@RequestParam Integer page,
corrigido

2024-07-12 22:42 UTC, magneon approved these changes

2024-07-12 22:42 UTC, merged